name: publish

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
            npm install
            npm run build
        env: 
          VUE_APP_API_KEY: ${{ secrets.API_KEY }}
          VUE_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          VUE_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          VUE_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
          VUE_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          VUE_APP_ID: ${{ secrets.APP_ID }}
          VUE_APP_DATABASE_URL: ${{ secrets.APP_DATABASE_URL }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.VUE_CHAT }}
          publish_dir: ./dist
